version: "3.8"

services:
  app:
    build: .
    command: yarn dev
    container_name: prasomar-api
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - TYPEORM_HOST=db
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image:  'postgres:latest'
    container_name: prasomar-db
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgres/data

volumes:
  pgdata:
    driver: local
