version: "3.9"

services:
  app:
    build: .
    command: yarn dev
    container_name: prasomar-api
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image:  'postgres:latest'
    container_name: prasomar-db
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - ./pgdata:/var/lib/postgres/data

volumes:
  pgdata:
    driver: local
